name = "crypto-alerts-worker"
main = "worker.js"
compatibility_date = "2024-09-01"

kv_namespaces = [
  { binding = "USER_DB", id = "77306c724f89400685ec6a210d672a2d" }
]

[vars]
BOT_TOKEN = "your-telegram-bot-token"
ADMIN_PASSWORD = "your-admin-password"
WORKER_DOMAIN = "crypto-alerts-worker.premiumrays01.workers.dev"
