name = "crypto-signal-hub"
main = "worker.js"
compatibility_date = "2025-09-09"
type = "javascript"

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_HERE"
COINGECKO_API = "https://api.coingecko.com/api/v3"
RUGDOC_API = "YOUR_RUGDOC_FLAGGED_TOKENS_API"
TG_CHANNEL_IDS = "CHANNEL_ID_1,CHANNEL_ID_2"

kv_namespaces = [
  { binding = "USERS_KV", id = "YOUR_USERS_KV_ID" },
  { binding = "ALERTS_KV", id = "YOUR_ALERTS_KV_ID" },
  { binding = "SIGNALS_KV", id = "YOUR_SIGNALS_KV_ID" },
  { binding = "MEMECOINS_KV", id = "YOUR_MEMECOINS_KV_ID" },
  { binding = "EVENTS_KV", id = "YOUR_EVENTS_KV_ID" },
  { binding = "WALLET_KV", id = "YOUR_WALLET_KV_ID" }
]

[[triggers.crons]]
schedule = "*/1 * * * *"

[[triggers.crons]]
schedule = "*/5 * * * *"

[[triggers.crons]]
schedule = "*/30 * * * *"
