name = "crypto-alerts-worker"
main = "worker.js"
compatibility_date = "2025-09-09"
type = "javascript"

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
COINGECKO_API = "https://api.coingecko.com/api/v3"
TG_CHANNEL_IDS = "CHANNEL_ID_1,CHANNEL_ID_2"

kv_namespaces = [
  { binding = "USERS_KV", id = "YOUR_USERS_KV_ID" },
  { binding = "ALERTS_KV", id = "YOUR_ALERTS_KV_ID" },
  { binding = "SIGNALS_KV", id = "YOUR_SIGNALS_KV_ID" },
  { binding = "MEMECOINS_KV", id = "YOUR_MEMECOINS_KV_ID" },
  { binding = "EVENTS_KV", id = "YOUR_EVENTS_KV_ID" },
  { binding = "WALLET_KV", id = "YOUR_WALLET_KV_ID" }
]

[triggers]
crons = ["*/5 * * * *"]  # Every 5 min – free-tier worker cron
